# Generated by Django 4.1.9 on 2023-05-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_teacher'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
        migrations.AlterField(
            model_name='task',
            name='appointor_teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='appointor_tasks', through='tasks.AppointedTask', to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='task',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', through='tasks.AppointedTask', to='users.student'),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskgroup'),
        ),
    ]
