# Generated by Django 4.1.9 on 2023-05-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_teacher'),
        ('tasks', '0002_taskgroup_remove_task_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='tasks.AppointedTask', to='users.student'),
        ),
    ]
