# Generated by Django 4.1.9 on 2023-05-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_teacher'),
        ('tasks', '0003_alter_task_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='appointor_teachers',
            field=models.ManyToManyField(related_name='appointor_tasks', through='tasks.AppointedTask', to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='task',
            name='students',
            field=models.ManyToManyField(related_name='tasks', through='tasks.AppointedTask', to='users.student'),
        ),
    ]
